export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const SUCCESS = "QUIZ_LIST/SUCCESS";
export const ERROR = "QUIZ_LIST/ERROR";

export const NEXT_QUESTION = "QUIZ/NEXT_QUESTION";
export const FINISHED = "QUIZ/FINISHED";
export const RETRY_QUIZ = "QUIZ/RETRY_QUIZ";
export const QUIZ_SET_STATE = "QUIZ/QUIZ_SET_STATE";
export const SET_QUIZ = "QUIZ/SET_QUIZ";

export const ADD_QUESTION = "CREATOR/ADD_QUESTION"
export const RESET_QUIZ = "CREATOR/RESET_QUIZ";

export const AUTH_SUCCESS = "AUTH/AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH/AUTH_LOGOUT";
export const AUTH_ERROR = "AUTH/AUTH_ERROR";
export const AUTH_CLEAR_ERROR = "AUTH/AUTH_CLEAR_ERROR";
